name: Publish packages

on:
  push:
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: true
      attestations: true

  # npm-login:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: '24'
  #         registry-url: 'https://registry.npmjs.org'
  #
  # npm-puiblish:
  #   needs: npm-login
  #   uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
  #   secrets:
  #     NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
  #   with:
  #     generate: true
  #     package-name: "@openscad/tree-sitter-openscad"
  # crates:
  #   uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
  #   secrets:
  #     CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
  #   with:
  #     generate: true
  #     package-name: "tree-sitter-openscad-ng"
  # pypi:
  #   uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
  #   secrets:
  #     PYPI_API_TOKEN: ${{secrets.PYPI_TOKEN}}
  #   with:
  #     generate: true
